version: '2'

services:

  # Core services
  core:
    build: ./core
    privileged: true
    labels:
      io.balena.features.balena-api: 1
      io.balena.features.supervisor-api: 1
      io.balena.features.balena-socket: 1
