#FROM balenalib/%%BALENA_MACHINE_NAME%%-node:12-run
FROM node:12


ENV DBUS_SYSTEM_BUS_ADDRESS=unix:path=/host/run/dbus/system_bus_socket
#RUN install_packages dbus
RUN apt-get update && apt-get install -y \
    dbus

COPY . /usr/src/testbot
WORKDIR /usr/src/testbot
RUN npm install -g typescript@4.0.5
RUN npm install
RUN tsc --version
RUN tsc


EXPOSE 8080

RUN chmod +x /usr/src/testbot/entry.sh
ENTRYPOINT [ "/usr/src/testbot/entry.sh"]
