# --- Installing Stage ---

FROM balenalib/%%BALENA_MACHINE_NAME%%-alpine-node:12-build as build

WORKDIR /usr/src/app
ENV UDEV=1
COPY package.json .

RUN  res=0; ( cp /run/secrets/.npmrc . && npm install ) || res=1; rm .npmrc; exit $res

# --- Result image ---

FROM balenalib/%%BALENA_MACHINE_NAME%%-alpine-node:12-run as result
WORKDIR /usr/src/app

ENV UDEV=1
RUN apk add util-linux
COPY --from=build /usr/src/app/node_modules ./node_modules
COPY . .

CMD ["node", "index.js"]

VOLUME /images
